security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: plain
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    role_hierarchy:

#        ROLE_ADMIN:
#            - ROLE_USER
#            - ROLE_LECTURER
#            - ROLE_SONATA_ADMIN

        ROLE_CONFERENCE_READER:
            - ROLE_ADMIN_COM_CONFERENCE_VIEW
            - ROLE_ADMIN_COM_CONFERENCE_EXPORT
            - ROLE_ADMIN_COM_CONFERENCE_LIST
            - ROLE_ADMIN_RESEARCH_CONFERENCE_VIEW
            - ROLE_ADMIN_RESEARCH_CONFERENCE_EXPORT
            - ROLE_ADMIN_RESEARCH_CONFERENCE_LIST
            - ROLE_ADMIN_CONFERENCE_LECTURER_LIST
            - ROLE_ADMIN_CONFERENCE_LECTURER_VIEW
            - ROLE_ADMIN_CONFERENCE_LECTURER_EXPORT

        ROLE_JOURNAL_READER:
#            - ROLE_ADMIN_JOURNAL_LIST
#            - ROLE_ADMIN_JOURNAL_VIEW
#            - ROLE_ADMIN_JOURNAL_EXPORT
            - ROLE_ADMIN_RESEARCH_JOURNAL_LIST
            - ROLE_ADMIN_RESEARCH_JOURNAL_VIEW
            - ROLE_ADMIN_RESEARCH_JOURNAL_EXPORT
            - ROLE_ADMIN_COM_JOURNAL_LIST
            - ROLE_ADMIN_COM_JOURNAL_VIEW
            - ROLE_ADMIN_COM_JOURNAL_EXPORT

        ROLE_INTELLECTUAL_PROPERTY_READER:
#            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LIST
#            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_VIEW
#            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_EXPORT
            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_LIST
            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_VIEW
            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_EXPORT
            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_LIST
            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_VIEW
            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_EXPORT

        ROLE_BOOK_READER:
            - ROLE_ADMIN_BOOK_LIST
            - ROLE_ADMIN_BOOK_VIEW
            - ROLE_ADMIN_BOOK_EXPORT
            - ROLE_ADMIN_COM_BOOK_LIST
            - ROLE_ADMIN_COM_BOOK_VIEW
            - ROLE_ADMIN_COM_BOOK_EXPORT
            - ROLE_ADMIN_RESEARCH_BOOK_LIST
            - ROLE_ADMIN_RESEARCH_BOOK_VIEW
            - ROLE_ADMIN_RESEARCH_BOOK_EXPORT

        ROLE_ADDITIONAL_OUTPUT_READER:
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LIST
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_VIEW
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_EXPORT

        ROLE_COMMUNITY_SERVICE_READER:
            - ROLE_ADMIN_COMMUNITY_SERVICE_LIST
            - ROLE_ADMIN_COMMUNITY_SERVICE_VIEW
            - ROLE_ADMIN_COMMUNITY_SERVICE_EXPORT

        ROLE_RESEARCH_READER:
            - ROLE_ADMIN_RESEARCH_LIST
            - ROLE_ADMIN_RESEARCH_VIEW
            - ROLE_ADMIN_RESEARCH_EXPORT

        ROLE_CONFERENCE_ADMIN:
            - ROLE_CONFERENCE_READER
            - ROLE_ADMIN_COM_CONFERENCE_EDIT
            - ROLE_ADMIN_COM_CONFERENCE_CREATE
            - ROLE_ADMIN_COM_CONFERENCE_DELETE

            - ROLE_ADMIN_RESEARCH_CONFERENCE_EDIT
            - ROLE_ADMIN_RESEARCH_CONFERENCE_CREATE
            - ROLE_ADMIN_RESEARCH_CONFERENCE_DELETE

#            - ROLE_ADMIN_APP_CONFERENCE_LIST
            - ROLE_ADMIN_APP_CONFERENCE_EDIT
            - ROLE_ADMIN_APP_CONFERENCE_CREATE
            - ROLE_ADMIN_APP_CONFERENCE_DELETE
#            - ROLE_ADMIN_APP_CONFERENCE_VIEW
#            - ROLE_ADMIN_APP_CONFERENCE_EXPORT

            - ROLE_ADMIN_CONFERENCE_LECTURER_EDIT
            - ROLE_ADMIN_CONFERENCE_LECTURER_CREATE
            - ROLE_ADMIN_CONFERENCE_LECTURER_DELETE


        ROLE_JOURNAL_ADMIN:
            - ROLE_JOURNAL_READER
            - ROLE_ADMIN_JOURNAL_EDIT
            - ROLE_ADMIN_JOURNAL_CREATE
            - ROLE_ADMIN_JOURNAL_DELETE

            - ROLE_ADMIN_RESEARCH_JOURNAL_EDIT
            - ROLE_ADMIN_RESEARCH_JOURNAL_CREATE
            - ROLE_ADMIN_RESEARCH_JOURNAL_DELETE

            - ROLE_ADMIN_COM_JOURNAL_EDIT
            - ROLE_ADMIN_COM_JOURNAL_CREATE
            - ROLE_ADMIN_COM_JOURNAL_DELETE

            - ROLE_ADMIN_JOURNAL_LECTURER_LIST
            - ROLE_ADMIN_JOURNAL_LECTURER_EDIT
            - ROLE_ADMIN_JOURNAL_LECTURER_CREATE
            - ROLE_ADMIN_JOURNAL_LECTURER_DELETE
            - ROLE_ADMIN_JOURNAL_LECTURER_VIEW
            - ROLE_ADMIN_JOURNAL_LECTURER_EXPORT

        ROLE_INTELLECTUAL_PROPERTY_ADMIN:
            - ROLE_INTELLECTUAL_PROPERTY_READER
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_EDIT
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_CREATE
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_DELETE

            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_EDIT
            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_CREATE
            - ROLE_ADMIN_COM_INTELLECTUAL_PROPERTY_DELETE

            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_EDIT
            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_CREATE
            - ROLE_ADMIN_RESEARCH_INTELLECTUAL_PROPERTY_DELETE

            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_LIST
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_EDIT
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_CREATE
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_DELETE
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_VIEW
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_LECTURER_EXPORT

        ROLE_BOOK_ADMIN:
            - ROLE_BOOK_READER
            - ROLE_ADMIN_BOOK_EDIT
            - ROLE_ADMIN_BOOK_CREATE
            - ROLE_ADMIN_BOOK_DELETE

            - ROLE_ADMIN_COM_BOOK_EDIT
            - ROLE_ADMIN_COM_BOOK_CREATE
            - ROLE_ADMIN_COM_BOOK_DELETE

            - ROLE_ADMIN_RESEARCH_BOOK_EDIT
            - ROLE_ADMIN_RESEARCH_BOOK_CREATE
            - ROLE_ADMIN_RESEARCH_BOOK_DELETE

            - ROLE_ADMIN_BOOK_LECTURER_LIST
            - ROLE_ADMIN_BOOK_LECTURER_EDIT
            - ROLE_ADMIN_BOOK_LECTURER_CREATE
            - ROLE_ADMIN_BOOK_LECTURER_DELETE
            - ROLE_ADMIN_BOOK_LECTURER_VIEW
            - ROLE_ADMIN_BOOK_LECTURER_EXPORT

        ROLE_CONFERENCE_ORGANIZER_ADMIN:
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_LIST
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_EDIT
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_CREATE
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_VIEW
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_DELETE
            - ROLE_ADMIN_CONFERENCE_ORGANIZER_EXPORT

        ROLE_EMPLOYMENT_CONTRACT_ADMIN:
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_LIST
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_EDIT
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_CREATE
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_VIEW
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_DELETE
            - ROLE_ADMIN_EMPLOYMENT_CONTRACT_EXPORT

        ROLE_ADDITIONAL_OUTPUT_ADMIN:
            - ROLE_ADDITIONAL_OUTPUT_READER
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_EDIT
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_CREATE
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_DELETE

            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_LIST
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_EDIT
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_CREATE
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_DELETE
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_VIEW
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_LECTURER_EXPORT

        ROLE_RESEARCH_ADMIN:
            - ROLE_RESEARCH_READER
            - ROLE_ADMIN_RESEARCH_EDIT
            - ROLE_ADMIN_RESEARCH_CREATE
            - ROLE_ADMIN_RESEARCH_DELETE
            - ROLE_ADMIN_RESEARCH_LECTURER_LIST
            - ROLE_ADMIN_RESEARCH_LECTURER_EDIT
            - ROLE_ADMIN_RESEARCH_LECTURER_CREATE
            - ROLE_ADMIN_RESEARCH_LECTURER_DELETE
            - ROLE_ADMIN_RESEARCH_LECTURER_VIEW
            - ROLE_ADMIN_RESEARCH_LECTURER_EXPORT
            - ROLE_ADMIN_RESEARCH_LECTURER_LIST

        ROLE_COMMUNITY_SERVICE_ADMIN:
            - ROLE_COMMUNITY_SERVICE_READER
            - ROLE_ADMIN_COMMUNITY_SERVICE_EDIT
            - ROLE_ADMIN_COMMUNITY_SERVICE_CREATE
            - ROLE_ADMIN_COMMUNITY_SERVICE_DELETE
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_LIST
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_EDIT
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_CREATE
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_DELETE
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_VIEW
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_EXPORT
            - ROLE_ADMIN_COMMUNITY_SERVICE_LECTURER_LIST
            - ROLE_ADMIN_COMMUNITY_SERVICE_PARTNER_EDIT
            - ROLE_ADMIN_COMMUNITY_SERVICE_PARTNER_CREATE
            - ROLE_ADMIN_COMMUNITY_SERVICE_PARTNER_DELETE
            - ROLE_ADMIN_COMMUNITY_SERVICE_PARTNER_VIEW
            - ROLE_ADMIN_COMMUNITY_SERVICE_PARTNER_EXPORT


        ROLE_LECTURER_ADMIN:
            - ROLE_ADMIN_LECTURER_LIST
            - ROLE_ADMIN_LECTURER_EDIT
            - ROLE_ADMIN_LECTURER_CREATE
            - ROLE_ADMIN_LECTURER_VIEW
            - ROLE_ADMIN_LECTURER_DELETE
            - ROLE_ADMIN_LECTURER_EXPORT

        ROLE_FACULTY:
            - ROLE_UNIT
            - ROLE_ADMIN_COM_BOOK_LIST
            - ROLE_ADMIN_COM_BOOK_EXPORT
            - ROLE_ADMIN_COM_BOOK_VIEW
            - ROLE_CONFERENCE_READER
            - ROLE_JOURNAL_READER
            - ROLE_BOOK_READER
            - ROLE_INTELLECTUAL_PROPERTY_READER
            - ROLE_ADDITIONAL_OUTPUT_READER
            - ROLE_COMMUNITY_SERVICE_READER
            - ROLE_RESEARCH_READER

        ROLE_UNIT:
            - ROLE_ADMIN
            - ROLE_CONFERENCE_ORGANIZER_ADMIN
            - ROLE_EMPLOYMENT_CONTRACT_ADMIN

        ROLE_LECTURER:
            - ROLE_ADMIN
            - ROLE_CONFERENCE_ADMIN
            - ROLE_JOURNAL_ADMIN
            - ROLE_ADMIN_LECTURER_LIST
            - ROLE_INTELLECTUAL_PROPERTY_ADMIN
            - ROLE_ADDITIONAL_OUTPUT_ADMIN
            - ROLE_BOOK_ADMIN
            - ROLE_COMMUNITY_SERVICE_ADMIN
            - ROLE_PEOPLE_ADMIN
            - ROLE_RESEARCH_ADMIN


        ROLE_PEOPLE_ADMIN:
            - ROLE_ADMIN_PEOPLE_LIST
            - ROLE_ADMIN_PEOPLE_CREATE
            - ROLE_ADMIN_PEOPLE_EDIT
            - ROLE_ADMIN_PEOPLE_DELETE

        ROLE_USER:
#            - ROLE_ADMIN_JOURNAL_LIST
#            - ROLE_ADMIN_APP_CONFERENCE_LIST
            - ROLE_ADMIN_JOURNAL_VIEW
            - ROLE_ADMIN_RESEARCH_JOURNAL_VIEW
            - ROLE_ADMIN_RESEARCH_CONFERENCE_VIEW
            - ROLE_ADMIN_BOOK_VIEW
            - ROLE_ADMIN_COMMUNITY_SERVICE_VIEW
            - ROLE_ADMIN_ADDITIONAL_OUTPUT_VIEW
#            - ROLE_ADMIN_APP_CONFERENCE_VIEW
            - ROLE_ADMIN_INTELLECTUAL_PROPERTY_VIEW
            - ROLE_ADMIN_RESEARCH_VIEW


#        ROLE_ADMIN: [ROLE_USER, ROLE_YEAR_LECTURER]

    access_decision_manager:
        strategy: unanimous

    providers:

#        in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/profile, roles: ROLE_USER }
