#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admine

app_logout:
    path: /logout
    methods: GET