App\Entity\Configuration:
    type: entity
    table: configurations
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        machineName:
            type: string
            length: 255
        name:
            type: string
            length: 255
        description:
            type: text
